name: Approval-export-and-branch-solution

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'Name of the solution to work on from Power Platform'
        required: true
        default: app_sol
      solution_exported_folder:
        description: 'Folder name for staging the exported solution *do not change*'
        required: true
        default: out/exported/
      solution_folder:
        description: 'Staging the unpacked solution folder before check-in *do not change*'
        required: true
        default: out/solutions/
      solution_target_folder:
        description: 'Folder name to be created and checked in *do not change*'
        required: true
        default: solutions/

env:
  ENVIRONMENT_URL: secrets.DEV_ENV
  CLIENT_ID: secrets.CLIENT_ID
  TENANT_ID: secrets.TENANT_ID

permissions:
  contents: write
  pull-requests: write

jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: Install Power Platform CLI
      run: |
        Invoke-WebRequest -Uri https://aka.ms/powerplatform-vscode -OutFile powerplatform-vscode.msi
        Start-Process msiexec.exe -Wait -ArgumentList '/I powerplatform-vscode.msi /quiet /norestart'
        $env:Path += ";C:\Program Files\WindowsPowerShell\Modules"

    - name: Install PAC CLI
      uses: microsoft/powerplatform-actions/actions-install@v1
      id: install-pac

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v1
      with:
        environment-url: ${{ secrets.DEV_ENV }}
        app-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.Client_SPN }}
        tenant-id: ${{secrets.TENANT_ID}}

    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: ${{ secrets.DEV_ENV }}
        app-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.Client_SPN }}
        tenant-id: ${{secrets.TENANT_ID}}
        solution-name: app_sol
        solution-output-file: out/exported/app_sol.zip

    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v1
      with:
        solution-file: out/exported/app_sol.zip
        solution-folder: out/solutions/app_sol
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v1
      with:
        solution-folder: out/solutions/app_sol
        solution-target-folder: solutions/app_sol
        repo-token: ${{ secrets.GH_TOKEN }}
        allow-empty-commit: true

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GH_TOKEN }}
        commit-message: "feat: Update solution ${{ inputs.solution_name }}"
        title: "Update solution ${{ inputs.solution_name }}"
        body: "This PR updates the solution ${{ inputs.solution_name }} with the latest changes from the Power Platform environment."
        branch: "update-solution-${{ inputs.solution_name }}"
        base: main
        draft: false
        delete-branch: true

  approve-and-merge:
    runs-on: ubuntu-latest
    needs: export-from-dev
    steps:
    - name: Wait for manual approval
      run: |
        echo "Please manually approve the PR and resume the workflow."
        echo "Once approved, click 'Resume workflow' in the GitHub Actions UI."
      continue-on-error: true

    - name: Merge PR
      run: |
        echo "PR approved and merged!"
