name: export-and-branch-solution

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'Name of the solution to work on from Power Platform'
        required: true
        default: ALMLab
      solution_exported_folder:
        description: 'Folder name for staging the exported solution *do not change*'
        required: true
        default: out/exported/
      solution_folder:
        description: 'Staging the unpacked solution folder before check-in *do not change*'
        required: true
        default: out/solutions/
      solution_target_folder:
        description: 'Folder name to be created and checked in *do not change*'
        required: true
        default: solutions/

env:
  ENVIRONMENT_URL: 'https://org41c53d90.crm4.dynamics.com'
  CLIENT_ID: 'c37f4956-70a3-4e74-a2d2-225b579d1a21'
  TENANT_ID: '302edaf0-65d6-449a-a796-b83cfb733f0d'

permissions:
  contents: write

jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1
    steps:
    - uses: actions/checkout@v3  # Use the latest version of checkout action
      with:
        lfs: true

    # Step 1: Install Power Apps CLI manually using PowerShell
    - name: Install Power Apps CLI (PAC)
      run: |
        # Download and install Power Apps CLI
        Invoke-WebRequest -Uri "https://aka.ms/install-powerapps-cli" -OutFile "install-pac.ps1"
        Set-ExecutionPolicy Bypass -Scope Process -Force
        .\install-pac.ps1

    # Step 2: Verify Power Apps CLI (PAC) installation
    - name: Verify PAC Version
      run: pac --version

    # Step 3: Authenticate with Power Platform using 'who-am-i' action
    # - name: Who Am I Action (authenticate with Power Platform)
    #   uses: microsoft/powerplatform-actions/who-am-i@v1
    #   with:
    #     environment-url: ${{ env.ENVIRONMENT_URL }}
    #     app-id: ${{ env.CLIENT_ID }}
    #     client-secret: ${{ secrets.PowerPlatformSPN }}
    #     tenant-id: ${{ env.TENANT_ID }}

    # Step 4: Export Solution using Power Platform action
    - name: Export Solution Action
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: ${{ env.ENVIRONMENT_URL }}
        app-id: ${{ env.CLIENT_ID }}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{ env.TENANT_ID }}
        solution-name: ${{ github.event.inputs.solution_name }}
        solution-output-file: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}.zip

    # Step 5: Unpack the Solution
    - name: Unpack Solution Action
      uses: microsoft/powerplatform-actions/unpack-solution@v1
      with:
        solution-file: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}.zip
        solution-folder: ${{ github.event.inputs.solution_folder}}/${{ github.event.inputs.solution_name }}
        solution-type: 'Unmanaged'
        overwrite-files: true

    # Step 6: Prepare Solution for Pull Request
    - name: Branch Solution, Prepare for PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v1
      with:
        solution-folder: ${{ github.event.inputs.solution_folder}}/${{ github.event.inputs.solution_name }}
        solution-target-folder: ${{ github.event.inputs.solution_target_folder}}/${{ github.event.inputs.solution_name }}
        repo-token: ${{ secrets.GH_TOKEN }}
        allow-empty-commit: true
