name: Create and Push to New Branch

on:
  push:
    branches:
      - main # Trigger the workflow when there is a push to the main branch.

jobs:
  create-branch-and-push:
    runs-on: ubuntu-latest

    steps:
    # Check out the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Git
    - name: Set up Git
      run: |
        git config --global user.name "Faiza Riaz"
        git config --global user.email "faiza.riaz10@gmail.com"

    # Create a new branch
    - name: Create new branch
      run: |
        git checkout -b new-branch # Replace with your desired branch name

    # Make a simple change (e.g., creating a new file)
    - name: Create a new file
      run: |
        echo "This is a new file created on a new branch" > new-file.txt
        git add new-file.txt
        git commit -m "Add new file"

    # Push the changes to the new branch using the GitHub Personal Access Token
    - name: Push changes to new branch
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }} # Reference the stored secret
      run: |
        git remote set-url origin https://github-actions:${{ secrets.GH_TOKEN }}@github.com/anney1/github-action-repo.git
        git push origin new-branch || echo "Push failed due to a possible conflict"

    # Checkout the main branch and merge new-branch into it
    - name: Checkout main branch
      run: |
        git checkout main
        git pull origin main  # Pull the latest changes from the main branch

    # Fetch the latest changes from new-branch before merging
    - name: Fetch latest changes from new-branch
      run: |
        git fetch origin new-branch

    - name: Merge new-branch into main
      run: |
        git merge origin/new-branch --allow-unrelated-histories -m "Merge new-branch into main"  # Merge with unrelated histories

    # Push the changes to the main branch
    - name: Push merged changes to main branch
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }} # Reference the stored secret
      run: |
        git push origin main  # Push the merged changes to the main branch
