name: Create and Push to New Branch

on:
  push:
    branches:
      - main # Trigger the workflow when there is a push to the main branch.

jobs:
  create-branch-and-push:
    runs-on: ubuntu-latest

    steps:
    # Check out the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Git
    - name: Set up Git
      run: |
        git config --global user.name "Faiza Riaz"
        git config --global user.email "faiza.riaz10@gmail.com"

    # Create a new branch
    - name: Create new branch
      run: |
        git checkout -b new-branch # Replace with your desired branch name

    # Make a simple change (e.g., creating a new file)
    - name: Create a new file
      run: |
        echo "This is a new file created on a new branch" > new-file.txt
        git add new-file.txt
        git commit -m "Add new file"

    # Push the changes to the new branch
    - name: Push changes to new branch
      run: |
        git push origin new-branch # Push the changes to the new branch
